import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  resources: [
    {
      type: 'category',
      label: 'Doc',
      items: [
        {
          type: 'link',
          label: 'API Reference',
          href: 'https://docs.aws.amazon.com/appsync/latest/APIReference/Welcome.html',
        },
      ],
    },
    {
      type: 'category',
      label: 'Learn',
      items: [
        {
          type: 'link',
          label: 'Developer Guide',
          href: 'https://docs.aws.amazon.com/appsync/latest/devguide/what-is-appsync.html',
        },
        { type: 'autogenerated', dirName: 'learn' },
      ],
    },
    { type: 'doc', id: 'tooling', label: 'Tooling' },
  ],
};

export default sidebars;
